config/routes.rb
Depot::Application.routes.draw do
  get "admin/login"

  get "admin/logout"

  get "admin/index"

  resources :line_items

  resources :orders

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get "store/index"

  resources :products

  resources :users

   match ':controller(/:action(/:id))(.:format)'
end

app/models/order.rb
class Order < ActiveRecord::Base
 has_many :products,:through => :line_items
 has_many :line_items
  attr_accessible :address, :email, :name, :pay_type
  
  PAYMENT_TYPES = [
 [ "Debit Card",  "dc" ],
 [ "Credit Card", "cc" ],
 [ "Cash On Delivery", "cod" ],
]

validates_presence_of :name, :address, :email, :pay_type
validates_inclusion_of :pay_type, :in =>
PAYMENT_TYPES.map {|disp, value| value}

def add_line_items_from_cart(cart)
cart.items.each do |item|
li = LineItem.from_cart_item(item)
line_items << li
end
end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
# GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])  

     respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  
   end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
  # GET /orders/1
  # GET /orders/1.json
def bill
 @order = Order.find(params[:id])
   
   respond_to do |format|
      format.html # bill.html.erb
      format.json { render json: @order }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<!DOCTYPE html>
<html>
<style>
div.field
{
padding-top:5em;
padding-left:15em;
align:center;
}
div.actions
{
padding-left:15em;
}
</style>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :pay_type %><br />
    <%= f.text_field :pay_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</html>

app/views/orders/edit.html.erb
<!DOCTYPE html>
<html>
<style>
body
{
background-color:#E0EAFB;
}
h1
{
text-align:center;
color:brown;
}
</style>
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>
</html>

app/views/orders/index.html.erb
<!DOCTYPE html>
<html>
<style>
 body {
background: #E0EAFB;
}
 h1 {
color: #141 ;
font-family: sans-serif;
padding-left: 7em;
padding-top: 5em;
}
 link {
width: 5em;
display: block;
}
 select,  textarea,  input {
margin-left: 0.5em;
}
submit {
margin-left: 4em;
}
table
{
padding-left:15em;
}
 div {
margin: 0.5em 0;
}
</style>
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Order ID</th>    
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Pay type</th>
    
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td><%= order.name %></td>
    <td><%= order.address %></td>
    <td><%= order.email %></td>
    <td><%= order.pay_type %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Remove', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


</body>
</html>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<!DOCTYPE html>
<html>
<style>
 body {
background: #efe;
}
 h1 {
color: #dfd ;
background: #141 ;
font-family: sans-serif;
padding: 0.2em;
}
 
</style>
<p id="notice"><%= notice %></p>
<%= render 'info/bill' %>

</body>
</html>